apiVersion: v1
kind: Pod
metadata:
  name: httpd-nginx-pod
spec:
  initContainers:
    - name: init-container
      image: busybox
      command:
        - sh
        - '-c'
        - >-
          echo "<html><body><h1>Hello from Souhern star</h1></body></html>"
          > /shared/index.html
      volumeMounts:
        - name: shared-volume
          mountPath: /shared
  containers:
    - name: httpd-container
      image: httpd
      volumeMounts:
        - name: shared-volume
          mountPath: /usr/local/apache2/htdocs
  volumes:
    - name: shared-volume
      emptyDir: {}
