apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-deployment
  name: my-deployment
spec:
  ports:
  - name: deployment-lb
    nodePort: 30083
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-deployment
  type: NodePort
