apiVersion: v1
kind: Pod
metadata:
  name: env-configmap
spec:
  containers:
    - name: app
      command: ["/bin/sh", "-c", "echo $"]
      image: busybox:latest
      envFrom:
        - configMapRef:
            name: myconfigmap
